export const MAKE_PAYMENT_REQUEST = 'MAKE_PAYMENT_REQUEST';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_FAIL = 'MAKE_PAYMENT_FAIL';
export const MAKE_PAYMENT_RESET = 'MAKE_PAYMENT_RESET';
